install.packages("rmarkdown")
install.packages("OpenStreetMap")
install.packages("GISTools")
install.packages("rgdal")
install.packages("dplyr")
install.packages("sp")

library("OpenStreetMap")
library("GISTools")
library("rgdal")
library("dplyr")
library("sp")